routes/web.php
        // .............................. Route For VR Report Initial.....................................//
        // .............................. Route For VRChart...............................................//
        Route::get('/chart', 'VRChartController@index')->middleware('permission:VR-Chart');
        // .............................. Route For VR Report.............................................//
        Route::get('/report', 'VRReportController@index')->middleware('permission:VR-Report');
        // .............................. Route For VR Invoice............................................//
        Route::get('/invoice', 'VRInvoiceController@index');
        
        // .........................................GET JSON Data Using Ajax Call for VR Report......................................................//
        Route::get('/filterreport','VRReportController@VRReport')->middleware('permission:VR-Report');
        Route::get('/filter_summary_report','VRReportController@VRSummaryReport')->middleware('permission:VR-Report');
        
        Route::get('/init', 'VRReportController@init')->middleware('permission:VR-Report');
// ...............................................................................................//

        Route::get('init/invoice', 'VRInvoiceController@init')->middleware('permission:VR-Invoice|VR-Invoice-Payment');
// ............GET JSON Data Using Ajax Call for VR Invoice......................................................//

    });

    Route::group(['prefix' => 'sms'], function(){
        // .............................. Route For SMS Chart.............................................//
        Route::get('/chart', 'SMSChartController@index');
        // .............................. Route For SMS Report............................................//
        Route::get('/report', 'SMSReportController@index');
        // .............................. Route For SMS Invoice...........................................//
        Route::get('/invoice', 'SMSInvoiceController@index');
    });

    Route::group(['prefix' => 'pgw'], function(){
        // .............................. Route For PGW Chart.............................................//
        Route::get('/chart', 'PGWChartController@index');
        // .............................. Route For PGW Report............................................//
        Route::get('/report', 'PGWReportController@index');
        // .............................. Route For PGW Invoice...........................................//
        Route::get('/invoice', 'PGWInvoiceController@index');
    });





// ..........................GET JSON Data Using Ajax Call for VR Chart...........................//
    Route::group(['prefix' => 'vr',  'middleware' => 'permission:VR-Chart'], function(){
        Route::get('/toptenkam','VRChartController@VRTopTenKamChart');
        Route::get('/toptenclient','VRChartController@VRTopTenClientChart');
        Route::get('/transactionamount','VRChartController@VRDynamicChart');
        Route::get('/transactionamountfilter','VRChartController@VRDynamicChartFilter');
        Route::get('/operator','VRChartController@VROpearatorChart');
        Route::get('/transactioncount','VRChartController@VRTransactionCountChart');
        Route::get('/impactclient','VRChartController@VRImpactClientChart');
        Route::get('/hourwise','VRChartController@VRHourWiseChart');
        Route::get('/easy','VRChartController@VREasyChart');
        Route::get('/department','VRChartController@VRDepartmentChart');
//        Route::get('/dynamicchartcompare','VRChartController@VRDynamicChartCompareChart');
//        Route::get('/amountcompare','VRChartController@VRDailyChart');
    });
//Route::get('/vr/toptenclientcmg','VRChartController@VRTopTenClientBCMGChart');

// ...............................................................................................//


    Route::group(['prefix' => 'vr',  'middleware' => 'permission:VR-Invoice'], function(){

        Route::get('/summaryinvoice/invoice','VRInvoiceController@VRSummaryInvoice');
        Route::get('/operatorwiseinvoice/invoice','VRInvoiceController@VROperatorWiseInvoice');
        Route::get('/easyinvoice/invoice','VRInvoiceController@VREasyInvoice');
        Route::get('/easyqubee/invoice','VRInvoiceController@VREasyQubeeInvoice');
    });

    Route::group(['prefix' => 'vr',  'middleware' => 'permission:VR-Invoice-Payment'], function(){

        Route::get('/paidinvoice/invoice','VRInvoiceController@VRPaidInvoice');
        Route::get('/unpaidinvoice/invoice','VRInvoiceController@VRUnpaidInvoice');
        Route::get('/updatepayment/invoice','VRInvoiceController@VRUpdatePayment');
        Route::get('/invoice/invoice','VRInvoiceController@VRInvoice');
    });
// ...............................................................................................//

// .........................................GET JSON Data Using Ajax Call for SMS Chart......................................................//
    Route::group(['prefix' => 'sms',  'middleware' => 'permission:SMS-Chart'], function(){
        Route::get('/toptenkam','SMSChartController@SMSTopTenKamChart');
        Route::get('/toptencompany','SMSChartController@SMSTopTenCompanyChart');
        Route::get('/transactionamount','SMSChartController@SMSDynamicChart');
        Route::get('/transactionamountfilter','SMSChartController@SMSDynamicChartFilter');
        Route::get('/operator','SMSChartController@SMSOpearatorChart');
        Route::get('/transactioncount','SMSChartController@SMSTransactionCountChart');
        Route::get('/impactclient','SMSChartController@SMSImpactClientChart');
        Route::get('/industry','SMSChartController@SMSIndustryChart');
    //    Route::get('/hourwise','SMSChartController@SMSHourWiseChart');

    });

// ...............................................................................................//

// .........................................GET JSON Data Using Ajax Call for SMS Report......................................................//
    Route::group(['prefix' => 'sms',  'middleware' => 'permission:SMS-Report'], function(){

        Route::get('/init', 'SMSReportController@init');
        Route::get('/filterreport', 'SMSReportController@SMSReport');
    });

// ...............................................................................................//

// .........................................GET JSON Data Using Ajax Call for SMS Invoice......................................................//
    Route::group(['prefix' => 'sms',  'middleware' => 'permission:SMS-Invoice'], function(){

        Route::get('/init/invoice', 'SMSInvoiceController@init');
        Route::get('/invoice/summary/', 'SMSInvoiceController@SMSSummaryInvoice');
        Route::get('/invoice/invoice/', 'SMSInvoiceController@SMSInvoice');
        Route::get('/invoice/paid/', 'SMSInvoiceController@SMSPaid');
        Route::get('/invoice/unpaid/', 'SMSInvoiceController@SMSUnpaid');
        Route::get('/updatepayment/invoice', 'SMSInvoiceController@SMSPayment');
    });


// ...............................................................................................//


// .........................................GET JSON Data Using Ajax Call for PWG Chart......................................................//
    Route::group(['prefix' => 'pgw',  'middleware' => 'permission:PGW-Chart'], function(){
        Route::get('/toptencompany','PGWChartController@PGWTopTenCompanyChart');
        Route::get('/transactionamount','PGWChartController@PGWDynamicChart');
        Route::get('/transactionamountfilter','PGWChartController@PGWDynamicChartFilter');
        Route::get('/bank','PGWChartController@PGWBankChart');
        Route::get('/transactioncount','PGWChartController@PGWTransactionCountChart');
        Route::get('/impactclient','PGWChartController@PGWImpactClientChart');
        Route::get('/hourwise','PGWChartController@PGWHourWiseChart');
        Route::get('/easy','PGWChartController@PGWEasyChart');
        Route::get('/cardtype','PGWChartController@PGWCardTypeChart');
        Route::get('/assumption','PGWChartController@PGWAssumptionChart');
    //    Route::get('/dynamicchartcompare','PGWChartController@PGWDynamicChartCompareChart');
    //    Route::get('/amountcompare','PGWChartController@PGWDailyChart');

    });

// ...............................................................................................//

// ....................GET JSON Data Using Ajax Call for PGW Report..............................................//
    Route::group(['prefix' => 'pgw',  'middleware' => 'permission:PGW-Chart'], function(){

        Route::get('/init', 'PGWReportController@init');
        Route::get('/filterreport', 'PGWReportController@PGWReport');
    });


// ...............................................................................................//

// .........................................GET JSON Data Using Ajax Call for PGW Invoice......................................................//
    Route::group(['prefix' => 'pgw',  'middleware' => 'permission:PGW-Invoice'], function(){

        Route::get('/invoice', 'PGWInvoiceController@index');
    });

// ...............................................................................................//
    Route::resource('role', 'RoleController')->middleware('permission:Admin-Permission');
    Route::resource('user', 'UserController')->middleware('permission:Admin-Permission');

// ....................File Upload.........................................//
    Route::group(['prefix' => 'file',  'middleware' => 'permission:File-Upload'], function(){

        Route::get('/', 'FileUploadController@index');
        Route::post('/upload/excel', 'FileUploadController@uploadExcel');
        Route::post('/upload/seb_excel', 'FileUploadController@uploadSebExcel');

app/User.php
<?php
namespace App;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;
class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\Role;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use App\Log;
class UserController extends Controller
{
    use Log;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->log('User Control','User Control ','User');

        try{
            $users    = User::all();
            $allRoles = Role::all();
            $data['title']='User Management';
            return view('userdetails.user.index',compact(['users','allRoles','data']));
        }catch(\Exception $e){
            Log::error($e->getMessage());
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try{
            $allRoles = Role::all();
            return view('userdetails.user.create',compact('allRoles'));
        }catch(\Exception $e){
            Log::error($e->getmessage());
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $validator = Validator::make($request->all(), [
                'name' => 'required|string|max:255',
                'email' => 'required|string|email|max:255|unique:users',
                'password' => 'required|string|min:6|confirmed',
            ]);

            if ($validator->fails()) {
                return redirect('user/create')
                            ->withErrors($validator)
                            ->withInput();
            }
            $user= User::create([
                'name' => $request['name'],
                'email' => $request['email'],
                'password' => bcrypt($request['password']),
            ]);
            foreach ($request->roles as $role){
                $user->attachRole($role);
            }
            // $user->attachRole(Role::where('name','general-user')->first());
            return redirect('user')->withMessage('User Created');
        }catch(\Exception $e){
            Log::error($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // return "Show ".$id;
        abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try{
           $data['title']='User Management';
           $roles=Role::all();
           $user=User::find($id);
           return view('userdetails.user.edit',compact(['user','roles','data']));
       }catch(\Exception $e){
        Log::error($e->getMessage());
       }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{   
            $user=User::find($id);
            $roles=$request->roles;
            DB::table('role_user')->where('user_id',$id)->delete();

            foreach ($roles as $role){
                $user->attachRole($role);
            }

            return redirect('user')->withMessage('Updated');
        }catch(\Exception $e){
            Log::error($e->getMessage());
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         try{
            DB::table("users")->where('id',$id)->delete();
            return back()->withMessage('Role Deleted');
        }catch(\Exception $e){
            Log::error($e->getmessage());
        }
    }
}

resources/views/userdetails/user/create.blade.php
@extends('layouts.app')
@permission('Admin-Permission')
@section('content')

<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Registration
            </h1>
        </section>
            
        <!-- Main content -->
        <section class="content">
          <div class="row">
                <div class="col-md-12">
                  <div class="box box-primary">
                    <div class="box-header">
                      <h4 class="box-title">User Registration</h4>
                    </div>
                    <div class="box-body form-row">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-6 col-md-offset-2">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">Register</div>

                                        <div class="panel-body">
                                            <form class="form-horizontal" method="POST" action="{{ route('user.store') }}">
                                                {{ csrf_field() }}

                                                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                                    <label for="name" class="col-md-4 control-label">Name</label>

                                                    <div class="col-md-6">
                                                        <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                                        @if ($errors->has('name'))
                                                            <span class="help-block">
                                                                <strong>{{ $errors->first('name') }}</strong>
                                                            </span>
                                                        @endif
                                                    </div>
                                                </div>

                                                <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                                    <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                                                    <div class="col-md-6">
                                                        <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                                                        @if ($errors->has('email'))
                                                            <span class="help-block">
                                                                <strong>{{ $errors->first('email') }}</strong>
                                                            </span>
                                                        @endif
                                                    </div>
                                                </div>

                                                <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                                                    <label for="password" class="col-md-4 control-label">Password</label>

                                                    <div class="col-md-6">
                                                        <input id="password" type="password" class="form-control" name="password" required>

                                                        @if ($errors->has('password'))
                                                            <span class="help-block">
                                                                <strong>{{ $errors->first('password') }}</strong>
                                                            </span>
                                                        @endif
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                                                    <div class="col-md-6">
                                                        <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                  <label for="password-confirm" class="col-md-4 control-label">User Roles</label>
                                                  <div class="col-md-6">
                                                    <select name="roles[]" title="Role" class="selectpicker form-control" data-live-search="true" multiple>
                                                      @foreach($allRoles as $role)
                                                          <option value="{{$role->id}}">{{$role->name}}</option>
                                                      @endforeach
                                                    </select>
                                                 </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="col-md-6 col-md-offset-4">
                                                        <button type="submit" class="btn btn-primary">
                                                            Register
                                                        </button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div><!-- /.box -->
    </div>  
</div> <!-- row close -->
@endsection
@endpermission

resources/views/userdetails/user/edit.blade.php
@extends('layouts.app')
@permission('Admin-Permission')
@section('content')

<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Edit
            </h1>
        </section>
            
        <!-- Main content -->
        <section class="content">
          <div class="row">
                <div class="col-md-12">
                  <div class="box box-primary">
                    <div class="box-header">
                      <h4 class="box-title">User Role For {{$user->name}}</h4>
                    </div>
                    <div class="box-body form-row">
                        <form action="{{route('user.update',$user->id)}}" method="post" role="form" id="role-form-{{$user->id}}">
                            {{csrf_field()}}
                            {{method_field('PATCH')}}
                            <div class="form-group">
                              <select name="roles[]" title="Role" class="selectpicker form-control" data-live-search="true" multiple>
                                @foreach($roles as $role)
                                    <option value="{{$role->id}}">{{$role->name}}</option>
                                @endforeach
                            </select>

                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div><!-- /.box -->
    </div>  
</div> <!-- row close -->
@endsection
@endpermission

resources/views/userdetails/user/index.blade.php
@extends('layouts.app')
@permission('Admin-Permission')
@section('content')
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Users
            </h1>
        </section>
            
        <!-- Main content -->
        <section class="content">
          <div class="row">
                <div class="col-md-12">
                  <div class="box box-primary">
                    <div class="box-header">
                      <!-- <h4 class="box-title">Filters</h4> -->
                    </div>
                    <div class="box-body">
                    <a class="btn btn-success" href="{{route('user.create')}}"> Create User</a>
                      <table class="table table-bordered">
                          <tr>
                              <th>Name of User</th>
                              <th>Roles</th>
                              <th>Action</th>
                          </tr>
                          @forelse($users as $user)
                              <tr>
                                  <td>{{$user->name}}</td>
                                  <td>
                                      @foreach($user->roles as $role)
                                          {{$role->name}}
                                      @endforeach

                                  </td>

                                  <td>

                                    <div class="col-md-12">
                                      <!-- Button trigger modal -->
                                      <div class="col-md-6 pull-left">
                                      <a href="user/{{$user->id}}/edit/" type="button" class="btn btn-primary btn-sm" style='width:100%' id="{{$user->id}}">
                                          Edit
                                      </a>
                                    </div>
                                      <form action="{{route('user.destroy',$user->id)}}"  method="POST">
                                         {{csrf_field()}}
                                         {{method_field('DELETE')}}
                                       <div class="col-md-6 pull-right">
                                         <input id = "delete" style=' width:100%;' class="btn btn-sm btn-danger" type="submit" value="Delete">
                                       </div>
                                       </form>
                                     </div>
                                  </td>
                              </tr>
                          @empty
                              <td>no users</td>
                          @endforelse
                      </table>
                  </div><!-- /.box -->
                </div>  
              </div>
          </div> <!-- row close -->
        </section>
        </div>
@endsection
@endpermission

resources/views/userdetails/user/userjs.blade.php
<script>
    @if(isset($error))
        swal("Hello world!");
    @endif
    @if(isset($info))
        swal("Hello world!");
    @endif
</script>